Update JSONchecker.yml

diff --git a/.github/workflows/JSONchecker.yml b/.github/workflows/JSONchecker.yml
--- a/.github/workflows/JSONchecker.yml
+++ b/.github/workflows/JSONchecker.yml
@@ -25,3 +25,7 @@ jobs:
         run: |
           python -m pip install jsonschema
           python scripts/ValidateJson.py
+          if [ -n "${{ steps.validate.outputs.error }}" ]; then
+            echo "Error: ${{ steps.validate.outputs.error }}"
+            exit 1
+          fi
